In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
from sklearn.preprocessing import LabelEncoder
from sklearn.model_selection import train_test_split
from sklearn.neural_network import MLPClassifier
from sklearn.metrics import accuracy_score
from sklearn.metrics import confusion_matrix
from sklearn import svm
from sklearn.neighbors import KNeighborsClassifier

In [2]:

# Read the training data from the Assignment1/dataset folder in the dataset
dataset = pd.read_csv('./dataset/adultTrain.data', sep=',', encoding='latin1', header= None)

#Then we read the test data from the Assignment1/dataset folder in the testset
testset = pd.read_csv('./dataset/adultTest.data', sep=',', encoding='latin1', header= None)
#print ("Dataset Lenght:: ", len(dataset))
#print ("Dataset Shape:: ", dataset.shape)

le=LabelEncoder()
tle=LabelEncoder()
for column in dataset:
    if dataset[column].dtypes == 'object':
        data=dataset[column]
        le.fit(data.values)
        dataset[column] = le.transform(dataset[column])
        
for column in testset:
    if testset[column].dtypes == 'object':
        testdata=testset[column]
        tle.fit(testdata.values)
        testset[column] = tle.transform(testset[column])

In [3]:
X_train = dataset.values[:, 0:14]
y_train = dataset.values[:, -1]

X_test = testset.values[:, 0:14]
y_test = testset.values[:, -1]

#print(X_test)

In [4]:
# Here we configure the architecure. These are hidden layers only
# The function will automatically create input nodes (one for each variable) and 
# one output node (for the target value)
#almost 64 input nodes
#one layer 20 nodes
mlp = MLPClassifier(hidden_layer_sizes=(10,10,10), max_iter=1000)
mlp.fit(X_train,y_train)

MLPClassifier(activation='relu', alpha=0.0001, batch_size='auto', beta_1=0.9,
       beta_2=0.999, early_stopping=False, epsilon=1e-08,
       hidden_layer_sizes=(10, 10, 10), learning_rate='constant',
       learning_rate_init=0.001, max_iter=1000, momentum=0.9,
       nesterovs_momentum=True, power_t=0.5, random_state=None,
       shuffle=True, solver='adam', tol=0.0001, validation_fraction=0.1,
       verbose=False, warm_start=False)

In [79]:
predictions_train = mlp.predict(X_train)
print("Confusion Matrix of NN Training set : ")
print(confusion_matrix(y_train,predictions_train))

[[24377   343]
 [ 6444  1397]]


In [ ]:
predictions_test = mlp.predict(X_test)
print("Confusion Matrix of NN Test set : ")
print( confusion_matrix(y_test,predictions_test))

In [82]:
accuracy = sum(1 for i in range(len(predictions_train)) if predictions_train[i] == y_train[i]) / float(len(predictions_train))
print("Accuracy of NN Training set : {0:.4f}".format(accuracy))

Accuracy of NN Training set : 0.7916


In [83]:
accuracy = sum(1 for i in range(len(predictions_test)) if predictions_test[i] == y_test[i]) / float(len(predictions_test))
print("Accuracy of NN Test set : {0:.4f}".format(accuracy))

Accuracy of NN Test set : 0.7921


In [84]:
svc_radial = svm.SVC()
svc_radial.fit(X_train, y_train)
predicted_train= svc_radial.predict(X_train)
predicted_test= svc_radial.predict(X_test)
#might take a while

In [85]:
cnf_matrix = confusion_matrix(y_train, predicted_train)
print("Confusion Matrix of SVM Training set : ")
print(cnf_matrix)

Confusion Matrix of SVM Training set : 
[[24720     0]
 [   42  7799]]


In [86]:
cnf_matrix = confusion_matrix(y_test, predicted_test)
print("Confusion Matrix of SVM Test set : ")
print(cnf_matrix)

Confusion Matrix of SVM Test set : 
[[12427     8]
 [ 3835    11]]


In [87]:
print("Accuracy of SVM Train set : {0:.4f}".format(accuracy_score(y_train, predicted_train)))

Accuracy of SVM Train set : 0.9987


In [88]:
print("Accuracy of SVM Test set : {0:.4f}".format(accuracy_score(y_test, predicted_test)))

Accuracy of SVM Test set : 0.7640


In [89]:
knn = KNeighborsClassifier(n_neighbors=20)
knn.fit(X_train, y_train)
predicted_train = knn.predict(X_train)
predicted_test = knn.predict(X_test)

In [90]:
cnf_matrix = confusion_matrix(y_train, predicted_train)
print("Confusion Matrix of KNN Training set : ")
print(cnf_matrix)

Confusion Matrix of KNN Training set : 
[[24419   301]
 [ 6065  1776]]


In [91]:
cnf_matrix = confusion_matrix(y_test, predicted_test)
print("Confusion Matrix of KNN Test set : ")
print(cnf_matrix)

Confusion Matrix of KNN Test set : 
[[12277   158]
 [ 3048   798]]


In [92]:
print("Accuracy of KNN Train set : {0:.4f}".format(accuracy_score(y_train, predicted_train)))

Accuracy of KNN Train set : 0.8045


In [93]:
print("Accuracy of KNN Test set : {0:.4f}".format(accuracy_score(y_test, predicted_test)))

Accuracy of KNN Test set : 0.8031
